# Generated by Django 5.2.14 on 2026-05-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0005_drop_season"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Source",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["short_name"], "verbose_name_plural": "categories"},
        ),
    ]
