# Generated by Django 5.2.14 on 2026-05-07 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("difficulty_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_problem_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="problem_sets",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=4)),
                ("title", models.CharField(max_length=200)),
                ("external_url", models.URLField(blank=True)),
                (
                    "solved_ac_tier_manual",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Bronze V"),
                            (2, "Bronze IV"),
                            (3, "Bronze III"),
                            (4, "Bronze II"),
                            (5, "Bronze I"),
                            (6, "Silver V"),
                            (7, "Silver IV"),
                            (8, "Silver III"),
                            (9, "Silver II"),
                            (10, "Silver I"),
                            (11, "Gold V"),
                            (12, "Gold IV"),
                            (13, "Gold III"),
                            (14, "Gold II"),
                            (15, "Gold I"),
                            (16, "Platinum V"),
                            (17, "Platinum IV"),
                            (18, "Platinum III"),
                            (19, "Platinum II"),
                            (20, "Platinum I"),
                            (21, "Diamond V"),
                            (22, "Diamond IV"),
                            (23, "Diamond III"),
                            (24, "Diamond II"),
                            (25, "Diamond I"),
                            (26, "Ruby V"),
                            (27, "Ruby IV"),
                            (28, "Ruby III"),
                            (29, "Ruby II"),
                            (30, "Ruby I"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="problemsets.problemset",
                    ),
                ),
            ],
            options={
                "ordering": ["problem_set_id", "order_index"],
            },
        ),
        migrations.AddIndex(
            model_name="problemset",
            index=models.Index(
                fields=["source", "year"], name="problemsets_source__02cb0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["problem_set", "order_index"],
                name="problemsets_problem_454cc5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.UniqueConstraint(
                fields=("problem_set", "order_index"),
                name="unique_problem_order_within_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.UniqueConstraint(
                fields=("problem_set", "label"), name="unique_problem_label_within_set"
            ),
        ),
    ]
