# Generated by Django 5.2.14 on 2026-05-08 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemAppearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=4)),
            ],
            options={
                "ordering": ["problem_set_id", "order_index"],
            },
        ),
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveConstraint(
            model_name="problem",
            name="unique_problem_order_within_set",
        ),
        migrations.RemoveConstraint(
            model_name="problem",
            name="unique_problem_label_within_set",
        ),
        migrations.RemoveIndex(
            model_name="problem",
            name="problemsets_problem_454cc5_idx",
        ),
        migrations.AlterField(
            model_name="problem",
            name="label",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="problem",
            name="order_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="problem_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="problemsets.problemset",
            ),
        ),
        migrations.AddField(
            model_name="problemappearance",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appearances",
                to="problemsets.problem",
            ),
        ),
        migrations.AddField(
            model_name="problemappearance",
            name="problem_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appearances",
                to="problemsets.problemset",
            ),
        ),
        migrations.AddIndex(
            model_name="problemappearance",
            index=models.Index(
                fields=["problem_set", "order_index"],
                name="problemsets_problem_86c083_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="problemappearance",
            index=models.Index(
                fields=["problem"], name="problemsets_problem_2ca50f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="problemappearance",
            constraint=models.UniqueConstraint(
                fields=("problem_set", "order_index"),
                name="unique_appearance_order_within_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemappearance",
            constraint=models.UniqueConstraint(
                fields=("problem_set", "label"),
                name="unique_appearance_label_within_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemappearance",
            constraint=models.UniqueConstraint(
                fields=("problem", "problem_set"), name="unique_problem_per_set"
            ),
        ),
    ]
