# Generated by Django 5.2.14 on 2026-05-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0003_migrate_problems_to_appearances"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="label",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="order_index",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="problem_set",
        ),
    ]
