# Generated by Django 5.2.14 on 2026-05-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0004_remove_problem_legacy_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problemset",
            name="season",
        ),
    ]
