# Generated by Django 5.2.14 on 2026-05-08 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0005_drop_season"),
        ("sources", "0002_rename_source_to_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="problemset",
            name="problemsets_source__02cb0c_idx",
        ),
        migrations.AlterField(
            model_name="problemset",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_problem_sets",
                to="sources.category",
            ),
        ),
        migrations.AddField(
            model_name="categorymembership",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sources.category"
            ),
        ),
        migrations.AddField(
            model_name="categorymembership",
            name="problem_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problemsets.problemset"
            ),
        ),
        migrations.AddField(
            model_name="problemset",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="problem_sets",
                through="problemsets.CategoryMembership",
                to="sources.category",
            ),
        ),
        migrations.AddIndex(
            model_name="problemset",
            index=models.Index(fields=["year"], name="problemsets_year_5d7494_idx"),
        ),
        migrations.AddIndex(
            model_name="categorymembership",
            index=models.Index(
                fields=["problem_set"], name="problemsets_problem_84bfed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="categorymembership",
            constraint=models.UniqueConstraint(
                fields=("category", "problem_set"), name="unique_category_membership"
            ),
        ),
    ]
