# Generated by Django 5.2.14 on 2026-05-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0007_migrate_source_to_membership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problemset",
            name="source",
        ),
    ]
