# Generated by Django 5.2.14 on 2026-05-09 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0008_drop_source_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollapsedNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collapsed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collapsed_by",
                        to="problemsets.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collapsed_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="problemsets_user_id_1b31aa_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "problem_set"),
                        name="unique_user_collapsed_node",
                    )
                ],
            },
        ),
    ]
