# Generated by Django 5.2.14 on 2026-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemsets", "0009_add_collapsed_node"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problemappearance",
            options={"ordering": ["problem_set_id", "label"]},
        ),
        migrations.RemoveConstraint(
            model_name="problemappearance",
            name="unique_appearance_order_within_set",
        ),
        migrations.RemoveIndex(
            model_name="problemappearance",
            name="problemsets_problem_86c083_idx",
        ),
        migrations.RemoveField(
            model_name="problemappearance",
            name="order_index",
        ),
        migrations.AddIndex(
            model_name="problemappearance",
            index=models.Index(
                fields=["problem_set", "label"], name="problemsets_problem_82cbc4_idx"
            ),
        ),
    ]
