# Generated by Django 5.2.14 on 2026-05-09 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(
                max_length=300,
                validators=[django.core.validators.MaxLengthValidator(300)],
            ),
        ),
    ]
